using System.Collections;
using System.Collections.Generic;

namespace ZuEngine.Service
{
	public enum EventIDs
	{
		ON_UPDATE = 0,
		ON_FIXUPDATE,
		ON_NETWORK_CONNECT_FINISH,
		ON_NETWORK_PLAYER_CONNECT,
		ON_NETWORK_ROOM_CREATED,

		INIT_LOADING_NETWORK_FINISH,
		MAINGAME_LOAD_RES_FINISH,

		UI_CONTROLLER_LEFT_ENTER,
		UI_CONTROLLER_RIGHT_ENTER,
		UI_CONTROLLER_GAS_ENTER,
		UI_CONTROLLER_BACK_ENTER,
		UI_CONTROLLER_BOOST_ENTER,
		UI_CONTROLLER_JUMP_CLICK,
		UI_CONTROLLER_SHOOT,

		UI_LOBBY_START_CLICK,

		ON_GOAL,
	}
}